### ISSUE TITLE
CORS XMLHttpRequest on Web

### ISSUE THREAD

**Issue by noga-dev** [xamantra/gh_trend#2]
Access to XMLHttpRequest at 'https://github.com/trending?spoken_language_code=en&since=daily' from origin 'https://agondev.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://user-images.githubusercontent.com/2067558/126079273-2f60cb03-60aa-41d7-827f-a1e063eb81b8.png)

**Comment by xamantra** [comment]
Hello @Agondev , thanks for this! I published a new version with your pull request. you can test that out and close this issue if you don't see any problems.
